ListaDeContatos/ListaDeContatos/Controllers/ContatoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using AutoMapper;
using ListaDeContatos.Dominio;
using ListaDeContatos.Models;
using ListaDeContatos.Negocio.Implementacao;
using ListaDeContatos.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;

namespace ListaDeContatos.Controllers
{
    [Authorize]
    public class ContatoController : Controller
    {
        private readonly ContatoNegocio _contatoNegocio;
        private readonly IMapper _mapper;

        public ContatoController(ContatoNegocio contatoNegocio, IMapper mapper)
        {
            _contatoNegocio = contatoNegocio;
            _mapper = mapper;
        }

        [Authorize(Roles = "Administrador,Completo,Basico")]
        public ActionResult ListarContatos()
        {
            try
            {               
                if (!string.IsNullOrEmpty((string)TempData["Sucesso"]))
                    ViewBag.Sucesso = (string)TempData["Sucesso"];

                if (!string.IsNullOrEmpty((string)TempData["Aviso"]))
                    ViewBag.Aviso = (string)TempData["Aviso"];

                if (!string.IsNullOrEmpty((string)TempData["Erro"]))
                    ViewBag.Erro = (string)TempData["Erro"];

                var retornoContato = _contatoNegocio.ListarContatos();

                if (retornoContato.Tipo == Enumerador.Tipo.Erro)
                {
                    ViewBag.Erro = retornoContato.Mensagem;
                    return View(new List<Contato>());
                }

                return View(retornoContato.Objeto);
            }
            catch (Exception ex)
            {
                ViewBag.Erro = "Erro: um erro ocorreu ao tentar carregar a lista de contatos, entre em contato com o Administrador";
                return View(new List<Contato>());
            }
        }

        [Authorize(Roles = "Administrador,Completo,Basico")]
        public ActionResult VisualizarContato(int id)
        {
            try
            {
                var retornoContato = _contatoNegocio.BuscarContato(id.ToString());

                if (retornoContato.Tipo == Enumerador.Tipo.Erro)
                {
                    TempData["Erro"] = retornoContato.Mensagem;
                    return RedirectToAction("ListarContatos");
                }
                if (retornoContato.Tipo == Enumerador.Tipo.Aviso)
                {
                    TempData["Aviso"] = retornoContato.Mensagem;
                    return RedirectToAction("ListarContatos");
                }


                var entidade = _mapper.Map<ContatoViewModel>(retornoContato.Objeto);

                return View(entidade);

            }
            catch (Exception ex)
            {
                TempData["Erro"] = "Erro: um erro ocorreu ao tentar carregar contato selecionado, entre em contato com o Administrador";
                return RedirectToAction(nameof(ListarContatos));
            }

        }
        
        [Authorize(Roles = "Administrador,Completo")]
        public ActionResult CriarContato()
        {
            try
            {

                AcessoApiExterna.AppCLiente acesso = new AcessoApiExterna.AppCLiente();
                var retorno = acesso.EstadoAsync().Result;

                List<Estado> lista = JsonConvert.DeserializeObject<List<Estado>>(retorno);
                ViewBag.Estado = lista;

                ViewBag.Cidade = JsonConvert.DeserializeObject<List<Cidade>>("[]");
                ViewBag.Bairro = JsonConvert.DeserializeObject<List<CEP>>("[]");

                return View();
            }
            catch (Exception)
            {
                TempData["Erro"] = "Erro: um erro ocorreu ao tentar carregar tela de novo contato, entre em contato com o Administrador";
                return RedirectToAction(nameof(ListarContatos));
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrador,Completo")]
        public ActionResult CriarContato(ContatoViewModel contatoViewModel)
        {

            try
            {
                AcessoApiExterna.AppCLiente acesso = new AcessoApiExterna.AppCLiente();
                var retorno = acesso.EstadoAsync().Result;
                //carregando Lista de Estados
                ViewBag.Estado = JsonConvert.DeserializeObject<List<Estado>>(retorno);

                if (contatoViewModel.Estado != null)
                {
                    var listaCidadeJson = acesso.CidadeAsync(contatoViewModel.Estado).Result;

                    ViewBag.Cidade = JsonConvert.DeserializeObject<List<Cidade>>(listaCidadeJson);

                }
                else
                    ViewBag.Cidade = JsonConvert.DeserializeObject<List<Cidade>>("[]");


                ViewBag.Bairro = JsonConvert.DeserializeObject<List<CEP>>("[]");

                if (ModelState.IsValid)
                {

                    var entidade = _mapper.Map<Contato>(contatoViewModel);

                    var retornoNegocio = _contatoNegocio.CriarContato(entidade);

                    if (retornoNegocio.Tipo == Enumerador.Tipo.Sucesso)
                    {
                        TempData["Sucesso"] = retornoNegocio.Mensagem;
                        return RedirectToAction(nameof(ListarContatos));
                    }
                    else if (retornoNegocio.Tipo == Enumerador.Tipo.Aviso)
                    {
                        ViewBag.Aviso = retornoNegocio.Mensagem;
                        return View(contatoViewModel);
                    }
                    else
                    {
                        TempData["Erro"] = retornoNegocio.Mensagem;
                        return RedirectToAction(nameof(ListarContatos));
                    }
                }

                return View(contatoViewModel);
            }
            catch (Exception ex)
            {
                TempData["Erro"] = "Erro: um erro ocorreu ao tentar salvar novo contato, entre em contato com o Administrador";
                return RedirectToAction(nameof(ListarContatos));
            }
        }

        [HttpGet]
        [Authorize(Roles = "Administrador,Completo")]
        public JsonResult CarregarCidade(string estado)
        {
            try
            {

                AcessoApiExterna.AppCLiente acesso = new AcessoApiExterna.AppCLiente();
                var retorno = acesso.CidadeAsync(estado).Result;

                var lista = JsonConvert.DeserializeObject<List<Cidade>>(retorno);

                var json = new JsonResult(lista);

                return json;

            }
            catch (Exception e)
            {
                Response.StatusCode = (int)HttpStatusCode.BadRequest;

                return Json(new { success = false });
            }
        }

        [HttpGet]
        [Authorize(Roles = "Administrador,Completo")]
        public JsonResult CarregarDadosCEP(string CEP)
        {
            try
            {

                AcessoApiExterna.AppCLiente acesso = new AcessoApiExterna.AppCLiente();
                var retorno = acesso.CEPAsync(CEP).Result;

                var cep = JsonConvert.DeserializeObject<CEP>(retorno);

                var json = new JsonResult(cep);

                return json;
            }
            catch (Exception e)
            {
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                
                return Json(new { success = false });
            }
        }

        [Authorize(Roles = "Administrador,Completo")]
        public ActionResult EditarContato(int id)
        {
            try
            {
                var retornoContato = _contatoNegocio.BuscarContato(id.ToString());

                AcessoApiExterna.AppCLiente acesso = new AcessoApiExterna.AppCLiente();
                var retornoEstado = acesso.EstadoAsync().Result;

                List<Estado> listaEstado = JsonConvert.DeserializeObject<List<Estado>>(retornoEstado);                
                ViewBag.Estado = new SelectList(listaEstado, "Sigla", "Nome", ((Contato)retornoContato.Objeto).Estado);

                var retornoCidade = acesso.CidadeAsync(((Contato)retornoContato.Objeto).Estado).Result;

                List<Cidade> listaCidade = JsonConvert.DeserializeObject<List<Cidade>>(retornoCidade);
                ViewBag.Cidade = new SelectList(listaCidade, "Nome", "Nome", ((Contato)retornoContato.Objeto).Cidade);
                
                var entidade = _mapper.Map<ContatoViewModel>(retornoContato.Objeto);

                return View(entidade);
            }
            catch (Exception ex)
            {
                TempData["Erro"] = "Erro: um erro ocorreu ao tentar carregar a tela de edição de contato, entre em contato com o Administrador";
                return RedirectToAction("ListarContatos");
            }

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrador,Completo")]
        public ActionResult EditarContato(int id, ContatoViewModel contatoViewModel)
        {
            try
            {
                AcessoApiExterna.AppCLiente acesso = new AcessoApiExterna.AppCLiente();
                var retorno = acesso.EstadoAsync().Result;
                //carregando Lista de Estados
                ViewBag.Estado = new SelectList(JsonConvert.DeserializeObject<List<Estado>>(retorno), "Sigla", "Nome", contatoViewModel.Estado);

                if (contatoViewModel.Estado != null)
                {
                    var listaCidadeJson = acesso.CidadeAsync(contatoViewModel.Estado).Result;

                    ViewBag.Cidade = new SelectList(JsonConvert.DeserializeObject<List<Cidade>>(listaCidadeJson), "Nome", "Nome", contatoViewModel.Cidade);

                }
                else

ListaDeContatos/ListaDeContatos/Controllers/SenhaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ListaDeContatos.Negocio.Implementacao;
using ListaDeContatos.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace ListaDeContatos.Controllers
{
    [Authorize]
    public class SenhaController : Controller
    {
        private readonly SenhaNegocio _senhaNegocio;
        private readonly RegistroNegocio _registroNegocio;

        public SenhaController(SenhaNegocio senhaNegocio, RegistroNegocio registroNegocio)
        {
            _senhaNegocio = senhaNegocio;
            _registroNegocio = registroNegocio;
        }

        [Authorize(Roles = "Administrador")]
        public ActionResult EditarSenha()
        {
            try
            {
                var listaUsuario = _registroNegocio.ListarUsuarios();

                if (listaUsuario.Tipo == Enumerador.Tipo.Erro)
                {
                    TempData["Erro"] = listaUsuario.Mensagem;
                    return RedirectToAction("ListarContatos");
                }

                ViewBag.ListaUsuarios = listaUsuario.Objeto;

                return View(new SenhaViewModel() { UsuarioId = "" });

            }
            catch (Exception ex)
            {
                TempData["Erro"] = "Erro: um erro ocorreu ao tentar carregar lista de usuários para edição de senha, entre em contato com o Administrador";
                return RedirectToAction(nameof(ListaDeContatos.Controllers.ContatoController.ListarContatos));
            }
        }

        [HttpPost]
        [Authorize(Roles = "Administrador")]
        [ValidateAntiForgeryToken]
        public ActionResult EditarSenha(SenhaViewModel senhaViewModel)
        {
            try
            {
                var listaUsuario = _registroNegocio.ListarUsuarios();

                if (listaUsuario.Tipo == Enumerador.Tipo.Erro)
                {
                    TempData["Erro"] = listaUsuario.Mensagem;
                    return RedirectToAction("ListarContatos");
                }

                ViewBag.ListaUsuarios = listaUsuario.Objeto;

                if (ModelState.IsValid)
                {
                    var retornoNegocio = _senhaNegocio.NovaSenha(senhaViewModel.UsuarioId).Result;

                    if (retornoNegocio.Tipo == Enumerador.Tipo.Erro)
                    {
                        ViewBag.Erro = retornoNegocio.Mensagem;
                        return View(senhaViewModel);
                    }
                    else if (retornoNegocio.Tipo == Enumerador.Tipo.Aviso)
                    {
                        ViewBag.Aviso = retornoNegocio.Mensagem;
                        return View(senhaViewModel);
                    }
                    else
                    {
                        ViewBag.Sucesso = retornoNegocio.Mensagem;
                        ViewBag.Senha = retornoNegocio.Objeto;

                        return View(senhaViewModel);

                    }

                }
                ViewBag.Senha = "";
                return View(senhaViewModel);
            }
            catch (Exception ex)
            {
                ViewBag.Erro = "Erro: um erro ocorreu ao tentar criar nova senha do usuário selecionado, entre em contato com o Administrador";
                return View(senhaViewModel);
            }
        }

    }
}

ListaDeContatos/ListaDeContatos/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ListaDeContatos</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>

    <style>
        .ly_nav {
            background-color: #2f80ed;
        }

        .ly_menu {
            color: #F2F2F2 !important;
        }

        .ly_menu:hover {
            
            font-weight: 600;
        }

    </style>

</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top ly_nav">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    
                    <li><a asp-area="" class="ly_menu" asp-controller="Registro" asp-action="ListaUsuarios">Registro</a></li>                    
                    <li><a asp-area="" class="ly_menu" asp-controller="AssociarUsuario" asp-action="ListarAssociarUsuario">Associar Usuário</a></li>
                    <li><a asp-area="" class="ly_menu" asp-controller="Contato" asp-action="ListarContatos">Contatos</a></li>
                    <li><a asp-area="" class="ly_menu" asp-controller="Senha" asp-action="EditarSenha">Senhas</a></li>
                    
                </ul>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">

        @if (!string.IsNullOrEmpty(@ViewBag.Sucesso))
        {
            <div class="alert alert-success alert-dismissible navbar-right alerta">
                <button class="close" data-dismiss="alert">X</button>
                <span>
                    @ViewBag.Sucesso
                </span>
            </div>
        }
        @if (!string.IsNullOrEmpty(@ViewBag.Aviso))
        {
            <div class="alert alert-warning alert-dismissible navbar-right alerta">
                <button class="close" data-dismiss="alert">X</button>
                <span>
                    @ViewBag.Aviso
                </span>
            </div>
        }
        @if (!string.IsNullOrEmpty(@ViewBag.Erro))
        {
            <div class="alert alert-danger alert-dismissible navbar-right alerta">
                <button class="close" data-dismiss="alert">X</button>
                <span>
                    @ViewBag.Erro
                </span>
            </div>
        }


        <img src="~/images/tela02.JPG" style="max-height:100px; max-height:80px" />
        @RenderBody()
        <hr />
        <footer style="background-color:#2F80ED;" class="navbar navbar-fixed-bottom ly_menu">
            <h3> &#9733; 2020 - Programa Teste</h3>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script src="~/lib/jquery-mask/jquery.mask.min.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>